### ISSUE TITLE
Talk dates have incorrect months

### ISSUE THREAD

**Issue by csabapalfi** [SaraVieira/graphql-portfolio#2]
See https://github.com/SaraVieira/graphql-portfolio/blob/master/src/server/data/talks.js vs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date 

> ...(note that the month is 0-based).

**Comment by SaraVieira** [comment]
Ohhhh, the more you know 😶

I'm going to fix that today and also use date fns to format the dates, Thank you  😊

**Comment by SaraVieira** [comment]
Fixed in the latest build 🎉

**Comment by csabapalfi** [comment]
Niice! 👍
